@startuml
skinparam linetype polyline
!define RECTANGLE class

class Account {
    + ID: int
    + name: String
    + email: String
    + username: String
    + password: String

    + roles: Collection<AccountRole>
}

enum AccountRole {
    USER
    ADMIN
    MODERATOR
}

class User {
    + bio: String
    + postRangeInKilometers: float
    + isBlocked: bool

    + privacySettings: PrivacySetting
    + posts: Collection<Post>
    + friends: Collection<User>
}

enum PrivacySetting {
    PRIVATE
    PUBLIC
}

class Post {
    + ID: int
    + content: String
    + image: Image
    + createdAt: DateTime
    + editedAt: DateTime 
    + likes: int
    + shares: int

    + author: User
    + comments: Collection<Comment>
    + fishingSpot: FishingSpot
}

class Comment {
    + ID: int
    + content: String
    + createdAt: DateTime
    + likes: int
    + shares: int

    + author: User
}

class Report {
    + ID: int
    + reason: String
    
    + status: ReportStatus
    + reporter: User
    + accused: User
}

enum ReportStatus {
    PENDING
    COMPLETED
}

class FishingSpot {
    + ID: int
    + name: String
    + location: Point
}

class AcceptedFishingSpot {
    + rating: float
    + details: String

    + posts: Collection<Post>
}

class ProposedFishingSpot {   
    + proposedAt: DateTime

    + proposer: User
}


Account <|-- User
Account -right- AccountRole
User "1" <--> "*" Post
Post "*" <-right-> "1" AcceptedFishingSpot
Post "1" --> "*" Comment
User "1" <-right- "*" Report
User -left- PrivacySetting
Report -right- ReportStatus
ProposedFishingSpot "*" -left-> "1" User
ProposedFishingSpot -left-|> FishingSpot
AcceptedFishingSpot --|> FishingSpot
Comment "*" -- "1" User


@enduml
