@startuml
skinparam linetype polyline
!define RECTANGLE class

class Account {
    + ID: int
    + name: String
    + surname: String
    + email: String
    + username: String
    + password: String

    + role: AccountRole
}

enum AccountRole {
    USER
    EMPLOYEE
    ADMIN
}

class User {
    + bio: String
    + privacySettings: String
    + postRange: String
    + isBlocked: bool

    + posts: Collection<Post>
    + friends: Collection<User>
}

class Post {
    + ID: int
    + textContent: String
    + image: Image
    + createdAt: DateTime
    + isEdited: bool
    + editedAt: DateTime
    + author: User
    + likes: int
    + shares: int

    + comments: Collection<Comment>
    + fishingSpot: FishingSpot
}

class Comment {
    + ID: int
    + content: String
    + author: User
    + timestamp: DateTime
}

class Report {
    + ID: int
    + reporter: User
    + reportedUser: User
    + reason: String
}

class FishingSpot {
    + ID: int
    + name: String
    + location: Location
}

class AcceptedFishingSpot {
    + rating: float
    + details: String

    + posts: Collection<Post>
}

class ProposedFishingSpot {
    + proposedBy: User
    + proposedTimestamp: DateTime
}


struct Location {
    + X: float
    + Y: float
}

Account <|-- User
Account -right- AccountRole
User "1" <--> "*" Post
Post "*" <-right-> "1" AcceptedFishingSpot
Post "1" --> "*" Comment
FishingSpot -- Location
User "1" <-left- "*" Report
ProposedFishingSpot "*" -left-> "1" User
ProposedFishingSpot -left-|> FishingSpot
AcceptedFishingSpot --|> FishingSpot

@enduml
